### ISSUE TITLE
Cleanup JetBrains, IntelliJ, etc. templates

### ISSUE THREAD

**Issue by orzechow** [dvcs/gitignore#41]
The templates around JetBrains IDEs are somewhat messy. The main template is `JetBrains.gitignore`, which is a clone of the github/gitignore template.

Now...
 - `Intellij.gitignore` links to `JetBrains.gitignore`, but
 - `Intellij.patch` is the corresponding patch, so
 - `JetBrains.patch` links to `Intellij.patch`, also
 - `Intellij+iml.gitignore` links to `JetBrains.gitignore`, while
 - `Intellij+iml.patch` is the actual patch

There are several aliases for JetBrains (AppCode, CLion, PhpStorm, PyCharm, RubyMine, WebStorm), but CLion is missing the patch and all of them are missing an `+iml` version (see https://github.com/joeblau/gitignore.io/issues/186 and https://github.com/joeblau/gitignore.io/issues/360)

**Comment by joeblau** [comment]
Fixed by #42
