### ISSUE TITLE
Why ignore yarn.lock and package-lock.json ?

### ISSUE THREAD

**Issue by gluons** [dvcs/gitignore#45]
I use [gitignore.io](https://github.com/joeblau/gitignore.io) that depend on this repo.

I see  that `yarn.lock` and `package-lock.json` have been ignored in [Node.gitignore](https://github.com/dvcs/gitignore/blob/d487ea2bc0c66ca2b88b9ba4795978deb9258a9d/templates/Node.gitignore#L58).

[Yarn website](https://yarnpkg.com/lang/en/docs/yarn-lock/) tell us to check `yarn.lock` into source control.
> All `yarn.lock` files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server.

<br>

**Why you ignore them?**

**Comment by joeblau** [comment]
If you think this should be updated, please submit a pull request.
