### ISSUE TITLE
Python venv files on Windows

### ISSUE THREAD

**Issue by kbakk** [dvcs/gitignore#9]
When running `python -m venv .` on Windows (Python 3), the following directories (not including subdirectories) and a file is created:

    Include/
    Lib/
    Scripts/
    pyvenv.cfg

See [documentation](https://docs.python.org/3/library/venv.html#creating-virtual-environments) for details. 

I suggest adding a section in Python for these (for instance named **venv (Windows)**)

**Comment by joeblau** [comment]
What do you think a `Python+venv` ?  We have something similar for Intellij which is `Intelllij+iml`

**Comment by kbakk** [comment]
First, it should be noted that I'm a Python beginner.

I'm not sure I agree to this (separate file Python+venv)... Noticing that Python.gitignore already have different virtual env sections, it seems more consistent with the existing form to put it here, and set a header for it (`# venv Windows` perhaps). It is also part of the Python Standard Library, so it belongs in the Python file _more_ than other existing sections (such as Django and Flask, being standalone web frameworks). 

I assume the most common use case is to add the file and modify it as needed (i.e. remove uneccessary sections). The cost of adding another section is thus not too high.  I also understand the need to keep the .gitignore file tidy - but I then suggest to remove the third-party tool sections and put those in separate files. 

Another thing, be aware that running venv it on Linux/MacOS will output a different file/directory structure, from the documentation:

    bin/ 
    lib/
    include/
    pyvenv.cfg

So it should probably be two separate sections (`# venv Windows` and `# venv *nix`).
